core/urls.py
from django.urls import path
from core.views import index, product_list_view, category_list_view, category_product_list_view, vendor_list_view, vendor_detail_view

app_name = 'core'

urlpatterns = [
    # Homepage
    path('', index, name='index'),
    path('products/', product_list_view, name='products'),
        
    # Category
    path('category/', category_list_view, name='category-list'),
    path('category/<cid>/', category_product_list_view, name='category-product-list'),
    
    # Vendor
    path('vendors/', vendor_list_view, name='vendor-list'),
    path('vendor/<vid>/', vendor_detail_view, name='vendor-detail'),
    
    
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sing-out/', views.logout_view, name='sing-out'),
]

templates/partials/footer.html
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
  <div class="container py-5">
    <div
      class="pb-4 mb-4"
      style="border-bottom: 1px solid rgba(226, 175, 24, 0.5)"
    >
      <div class="row g-4">
        <div class="col-lg-3">
          <a href="#">
            <h1 class="text-primary mb-0">Fruitables</h1>
            <p class="text-secondary mb-0">Fresh products</p>
          </a>
        </div>
        <div class="col-lg-6">
          <div class="position-relative mx-auto">
            <input
              class="form-control border-0 w-100 py-3 px-4 rounded-pill"
              type="number"
              placeholder="Your Email"
            />
            <button
              type="submit"
              class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white"
              style="top: 0; right: 0"
            >
              Subscribe Now
            </button>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="d-flex justify-content-end pt-3">
            <a
              class="btn btn-outline-secondary me-2 btn-md-square rounded-circle"
              href=""
              ><i class="fab fa-twitter"></i
            ></a>
            <a
              class="btn btn-outline-secondary me-2 btn-md-square rounded-circle"
              href=""
              ><i class="fab fa-facebook-f"></i
            ></a>
            <a
              class="btn btn-outline-secondary me-2 btn-md-square rounded-circle"
              href=""
              ><i class="fab fa-youtube"></i
            ></a>
            <a
              class="btn btn-outline-secondary btn-md-square rounded-circle"
              href=""
              ><i class="fab fa-linkedin-in"></i
            ></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row g-5">
      <div class="col-lg-3 col-md-6">
        <div class="footer-item">
          <h4 class="text-light mb-3">Why People Like us!</h4>
          <p class="mb-4">
            typesetting, remaining essentially unchanged. It was popularised in
            the 1960s with the like Aldus PageMaker including of Lorem Ipsum.
          </p>
          <a
            href=""
            class="btn border-secondary py-2 px-4 rounded-pill text-primary"
            >Read More</a
          >
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="d-flex flex-column text-start footer-item">
          <h4 class="text-light mb-3">Shop Info</h4>
          <a class="btn-link" href="">About Us</a>
          <a class="btn-link" href="">Contact Us</a>
          <a class="btn-link" href="">Privacy Policy</a>
          <a class="btn-link" href="">Terms & Condition</a>
          <a class="btn-link" href="">Return Policy</a>
          <a class="btn-link" href="">FAQs & Help</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="d-flex flex-column text-start footer-item">
          <h4 class="text-light mb-3">Account</h4>
          <a class="btn-link" href="">My Account</a>
          <a class="btn-link" href="">Shop details</a>
          <a class="btn-link" href="">Shopping Cart</a>
          <a class="btn-link" href="">Wishlist</a>
          <a class="btn-link" href="">Order History</a>
          <a class="btn-link" href="">International Orders</a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="footer-item">
          <h4 class="text-light mb-3">Contact</h4>
          <p>Address: 1429 Netus Rd, NY 48247</p>
          <p>Email: Example@gmail.com</p>
          <p>Phone: +0123 4567 8910</p>
          <p>Payment Accepted</p>
          <img src="img/payment.png" class="img-fluid" alt="" />
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Footer End -->

templates/partials/navbar.html
<!-- Navbar start -->
<div class="container-fluid fixed-top">
  {% if messages %}
    {% for message in messages %}
      <div class="msn alert-{{ message.tags }}" style="text-align: left; padding: 10px; border-radius: 10px; margin-top: 10px; margin-bottom: 10px;">{{ message }}</div>
    {% endfor %}
  {% endif %}

  <script>
    setTimeout(function () {
      $('.msn').alert('close')
    }, 2000)
  </script>

  <div class="container topbar bg-primary d-none d-lg-block">
    <div class="d-flex justify-content-between">
      <div class="top-info ps-2">
        <small class="me-3">
          <i class="fas fa-map-marker-alt me-2 text-secondary"></i>
          <a href="#" class="text-white">123 Street, New York</a>
        </small>
        <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
      </div>
      <div class="top-link pe-2">
        <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
        <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
      </div>
    </div>
  </div>
  <div class="container px-0">
    <nav class="navbar navbar-light bg-white navbar-expand-xl">
      <a href="index.html" class="navbar-brand"><h1 class="text-primary display-6">Fruitables</h1></a>
      <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"><span class="fa fa-bars text-primary"></span></button>
      <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
        <div class="navbar-nav mx-auto">
          <a href="{% url "core:index" %}" class="nav-item nav-link">Home</a>
          <a href="{% url "core:products" %}" class="nav-item nav-link">Products</a>
          <div class="nav-item dropdown">
            <a href="{% url "core:category-list" %}" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Categories</a>
            <div class="dropdown-menu m-0 bg-secondary rounded-0">

              {% for c in categories %}
              <a href="{% url "core:category-product-list" c.cid %}" class="dropdown-item">{{c.title}}</a>
              {% endfor %}

             <hr/>

              <a href="{% url "core:category-list" %}" class="dropdown-item">All Categories</a>
              
            </div>
          </div>
          <a href="{% url "core:vendor-list" %}" class="nav-item nav-link">Vendors</a>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
            <div class="dropdown-menu m-0 bg-secondary rounded-0">
              <a href="cart.html" class="dropdown-item">Cart</a>
              <a href="chackout.html" class="dropdown-item">Chackout</a>
              <a href="testimonial.html" class="dropdown-item">Testimonial</a>
              <a href="404.html" class="dropdown-item">404 Page</a>
            </div>
          </div>
          <a href="contact.html" class="nav-item nav-link">Contact</a>
        </div>
        <div class="d-flex m-4 me-0">
          <button class="btn-search btn border border-secondary btn-md-square rounded-circle bg-white me-4" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fas fa-search text-primary"></i></button>
          <a href="#" class="position-relative me-4 my-auto">
            <i class="fa fa-shopping-bag fa-2x"></i>
            <span class="position-absolute bg-secondary rounded-circle d-flex align-items-center justify-content-center text-dark px-1" style="top: -5px; left: 15px; height: 20px; min-width: 20px">3</span>
          </a>
          {% if request.user.is_authenticated %}
            <a href="{% url 'userauths:sing-out' %}" class="my-auto"><i class="fa fa-sign-out fa-2x"></i></a>
          {% else %}
            <a href="{% url 'userauths:sign-in' %}" class="my-auto me-4"><i class="fas fa-user fa-2x"></i></a>
          {% endif %}
        </div>
      </div>
    </nav>
  </div>
</div>
<!-- Navbar End -->

<!-- Modal Search Start -->
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content rounded-0">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body d-flex align-items-center">
        <div class="input-group w-75 mx-auto d-flex">
          <input type="search" class="form-control p-3" placeholder="keywords" aria-describedby="search-icon-1" />
          <span id="search-icon-1" class="input-group-text p-3"><i class="fa fa-search"></i></span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Search End -->