core/urls.py
from django.urls import path
from core.views import index, product_list_view, category_list_view, category_product_list_view, vendor_list_view, vendor_detail_view

app_name = 'core'

urlpatterns = [
    # Homepage
    path('', index, name='index'),
    path('products/', product_list_view, name='products'),
        
    # Category
    path('category/', category_list_view, name='category-list'),
    path('category/<cid>/', category_product_list_view, name='category-product-list'),
    
    # Vendor
    path('vendors/', vendor_list_view, name='vendor-list'),
    path('vendor/<vid>/', vendor_detail_view, name='vendor-detail'),
    
    
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = 'userauths'

urlpatterns = [
    path('sign-up/', views.register_view, name='sign-up'),
    path('sign-in/', views.login_view, name='sign-in'),
    path('sing-out/', views.logout_view, name='sing-out'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True, null=False)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    
    def __str__(self):
        return self.username
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username", 'style': 'width: 100%;', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email", 'style': 'width: 100%;', 'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password", 'style': 'width: 100%;', 'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password", 'style': 'width: 100%;', 'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User


#User = settings.AUTH_USER_MODEL

def register_view(request):        
    if request.method == 'POST':
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hey, {username}! You account was created successfully.')
            new_user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect ('core:index')            
        
    else:
        form = UserRegisterForm()
        
    context = {
        'form' : form,
    }
    
    return render(request, 'userauths/sign-up.html', context)

def login_view(request):    
    if request.user.is_authenticated:
        messages.warning(request, f"hey you are already logged in.")
        return redirect('core:index')
    
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(email=email) 
            user = authenticate(request, email=email, password=password)
            
            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in")
                return redirect("core:index")
        
            else:
                messages.warning(request, "User Does Not Exists. Create an account")         
            
            
        except:
            messages.warning(request, f'User with {email} does not exist')       
            
        
    
    return render(request, 'userauths/sign-in.html')
        
         
def logout_view(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% extends "base.html" %} 
{% load static %} 

{% block 'body' %}
<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
  <h1 class="text-center text-white display-6">Login</h1>
  <ol class="breadcrumb justify-content-center mb-0">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Pages</a></li>
    <li class="breadcrumb-item active text-white">Login</li>
  </ol>
</div>
<!-- Single Page Header End -->

<!-- Contact Start -->
<div class="container col-lg-6 contact py-5">
  <div class="container py-5">
    <div class="p-5 bg-light rounded">
      <div class="row g-4">
        <div class="col-12">
          <div class="text-center mx-auto" style="max-width: 700px">
            <h1 class="text-primary">Login</h1>
            <p class="mb-4">
              Don't have an account?
              <a href="{% url "userauths:sign-up" %}">Create here</a>.
            </p>
            {% if form.errors %}
            <div class="alert-danger" style="text-align: left">
              {{form.errors}}
            </div>
            {% endif %}
          </div>
        </div>

        <div class="col-lg-12">
          <form action="" method="POST">
            {% csrf_token %}
            <input
              required
              type="text"
              name="email"
              class="w-100 form-control border-0 py-3 mb-4"
              placeholder="Your Email"
            />
            <input
              required
              name="password"
              type="password"
              class="w-100 form-control border-0 py-3 mb-4"
              placeholder="Your Password"
            />

            <button
              class="w-100 btn form-control border-secondary py-3 bg-white text-primary"
              type="submit"
            >
              Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact End -->
{% endblock 'body' %}

templates/userauths/sign-up.html
{% extends "base.html" %} {% load static %} {% block 'body' %}

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
  <h1 class="text-center text-white display-6">Register</h1>
  <ol class="breadcrumb justify-content-center mb-0">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Pages</a></li>
    <li class="breadcrumb-item active text-white">Register</li>
  </ol>
</div>
<!-- Single Page Header End -->

<!-- Contact Start -->
            <div class="container col-lg-6 contact py-5">
  <div class="container py-5">
    <div class="p-5 bg-light rounded">
      <div class="row g-4">
        <div class="col-12">
          <div class="text-center mx-auto" style="max-width: 700px">
            <h1 class="text-primary">Create an Account</h1>
            <p class="mb-4">
              Already have an account?
              <a href="{% url "userauths:sign-in" %}">Login</a>.
            </p>
            {% if form.errors %}
            <div class="alert-danger" style="text-align: left; padding: 20px">
              {{form.errors}}
            </div>
            {% endif %}
          </div>
        </div>

        <div class="col-lg-12">
          <form action="" method="POST">
            {% csrf_token %}

            <div class="w-100 form-control border-0 py-3 mb-4">
              {{form.username}}
            </div>

            <div class="w-100 form-control border-0 py-3 mb-4">
              {{form.email}}
            </div>

            <div class="w-100 form-control border-0 py-3 mb-4">
              {{form.password1}}
            </div>

            <div class="w-100 form-control border-0 py-3 mb-4">
              {{form.password2}}
            </div>

            <button
              class="w-100 btn form-control border-secondary py-3 bg-white text-primary"
              type="submit"
            >
              Submit
            </button>

            {% comment %}
            <input
              type="text"
              class="w-100 form-control border-0 py-3 mb-4"
              placeholder="Your Name"
            />
            <input
              type="email"
              class="w-100 form-control border-0 py-3 mb-4"
              placeholder="Enter Your Email"
            />

            <button
              class="w-100 btn form-control border-secondary py-3 bg-white text-primary"
              type="submit"
            >
              Submit
            </button>
            {% endcomment %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact End -->
{% endblock 'body' %}